training:
  batch_size: 128
  learning_rate: 0.001
  epochs: 10
  data_dir: "data/oro"
  warmup_steps: 100
  total_steps: 1000
  num_features: 6
  model_name: "xlstm"  # Options: "SimpleNN" or "LSTM"
  output_size: 18

dataset:
  sequence_length_minutes: 60
  prediction_horizon: "next_one"
  time_interval_minutes: 5

simplenn:
  hidden_size: 280
  dropout: 0.1

lstm:
  hidden_size: 280
  num_layers: 2
  dropout: 0.1

xlstm:
  hidden_size: 256
  num_heads: 2
  layers: ["s", "m", "s"]
  proj_factor_slstm: 1.3333   # Approximately 4/3
  proj_factor_mlstm: 2
  dropout: 0.1